import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import { store } from "@/redux/store";
import Auth from "@/components/Auth";
import SharedComponents from "@/components/SharedComponents";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Deck Crafter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <Auth>
            <SharedComponents>
              {children}
            </SharedComponents>
          </Auth>
        </Providers>
      </body>
    </html >
  );
}